import random

print(" Welcome to the game!")
answer=input("do you want to play the game :")
answer.lower()
if answer!="yes":
    quit()

lower=input("enter the lower limit:")
if lower.isdigit():
    lower=int(lower)
else:
   print(" please enter a digit next time")
   quit()

upper=input("enter the upper limit :")
if upper.isdigit():
    upper=int(upper)
else:
   print(" please enter a digit next time")
   quit()

   

print("lets get started ")
print("the rule is simple you have to guess a random number generated by this computer and which lies in your given range")
print("and who does it in less turns will win")
r=random.randrange(lower,upper)
count=0
while(1):
    n=int(input("enter your guess :"))
    if n==r:
        print("yay! its correct")
        break
    elif n>r:
        print("no! its less than that")
    else:
        print("no! its greater than that")
    count=count+1
print("you took",count+1,"turns to guess")